@php
    $iconChoices = [
        'fa-solid fa-star' => 'Star',
        'fa-solid fa-heart' => 'Heart',
        'fa-solid fa-award' => 'Award',
        'fa-solid fa-trophy' => 'Trophy',
        'fa-solid fa-medal' => 'Medal',
        'fa-solid fa-crown' => 'Crown',
        'fa-solid fa-gem' => 'Gem',
        'fa-solid fa-lightbulb' => 'Lightbulb',
        'fa-solid fa-rocket' => 'Rocket',
        'fa-solid fa-bullseye' => 'Bullseye',
        'fa-solid fa-flag' => 'Flag',
        'fa-solid fa-shield-halved' => 'Shield',
        'fa-solid fa-handshake' => 'Handshake',
        'fa-solid fa-users' => 'Users',
        'fa-solid fa-people-group' => 'People Group',
        'fa-solid fa-earth-asia' => 'Globe',
        'fa-solid fa-building' => 'Building',
        'fa-solid fa-briefcase' => 'Briefcase',
        'fa-solid fa-chart-line' => 'Chart Line',
        'fa-solid fa-chart-simple' => 'Chart Simple',
        'fa-solid fa-clock' => 'Clock',
        'fa-solid fa-calendar-check' => 'Calendar Check',
        'fa-solid fa-bolt' => 'Bolt',
        'fa-solid fa-leaf' => 'Leaf',
        'fa-solid fa-seedling' => 'Seedling',
        'fa-solid fa-compass' => 'Compass',
        'fa-solid fa-map' => 'Map',
        'fa-solid fa-location-dot' => 'Location',
        'fa-solid fa-house' => 'House',
        'fa-solid fa-gears' => 'Gears',
        'fa-solid fa-wrench' => 'Wrench',
        'fa-solid fa-hammer' => 'Hammer',
        'fa-solid fa-circle-check' => 'Check Circle',
        'fa-solid fa-thumbs-up' => 'Thumbs Up',
        'fa-solid fa-comments' => 'Comments',
        'fa-solid fa-comment-dots' => 'Comment Dots',
        'fa-solid fa-book' => 'Book',
        'fa-solid fa-graduation-cap' => 'Graduation Cap',
        'fa-solid fa-camera' => 'Camera',
        'fa-solid fa-phone' => 'Phone',
        'fa-solid fa-envelope' => 'Envelope',
        'fa-solid fa-magnifying-glass' => 'Magnifying Glass',
        'fa-solid fa-scale-balanced' => 'Balance',
        'fa-solid fa-recycle' => 'Recycle',
        'fa-solid fa-industry' => 'Industry',
        'fa-solid fa-truck' => 'Truck',
        'fa-solid fa-boxes-stacked' => 'Boxes',
    ];
@endphp

@foreach($iconChoices as $iconClass => $label)
    <option value="{{ $iconClass }}" {{ $selected === $iconClass ? 'selected' : '' }}>{{ $label }}</option>
@endforeach
